window.farmerTranslations = window.farmerTranslations || {};
window.farmerTranslations.en = {
  language: 'English',
  languageLabel: '🌐 తెలుగు | English',
  common: {
    home: 'Home', dashboard: 'Dashboard', centers: 'Centers', bookings: 'Bookings', myBookings: 'My Bookings', procurement: 'Procurement', notifications: 'Notifications', profile: 'Profile', logout: 'Logout', login: 'Login', register: 'Register', back: 'Back', backDashboard: 'Back to Dashboard', cancel: 'Cancel', continue: 'Continue', confirm: 'Confirm Booking', viewBookings: 'View My Bookings', viewStatus: 'View Procurement Status', backHome: 'Back to Home', save: 'Save', close: 'Close', farmer: 'Farmer', select: 'Select', status: 'Status', date: 'Date', time: 'Time', crop: 'Crop', quantity: 'Quantity', center: 'Procurement Center', mobile: 'Mobile'
  },
  home: { how: 'How It Works', welcome: 'Manage your procurement, bookings, and center visits from one place.', nearby: 'Nearby Centers', viewCenters: 'View Centers', findCenter: 'Find Procurement Center', bookSlot: 'Book Slot', viewBookings: 'View Bookings', viewProcurement: 'View Procurement', viewNotifications: 'View Notifications', notifications: 'Check important updates about your bookings and procurement.' },
  login: { title: 'Farmer Login', phone: 'Mobile Number', phonePlaceholder: 'Enter your mobile number', password: 'Password', passwordPlaceholder: 'Enter your password', submit: 'Login', noAccount: "Don't have an account?", register: 'Register', invalid: 'The mobile number or password does not match your account.', noAccountFound: 'No account found. Please register first.' },
  registration: { title: 'Create Your Farmer Account', fullName: 'Full Name', fullNamePlaceholder: 'Enter your full name', phone: 'Mobile Number', password: 'Password', passwordPlaceholder: 'Create a password', confirmPassword: 'Confirm Password', confirmPlaceholder: 'Confirm your password', state: 'Select State', district: 'Select District', submit: 'Create Account', success: 'Registration successful! You can now login.' },
  center: { nearby: 'Nearby Procurement Centers', description: 'Find nearby procurement centers, check availability, and book your slot.', search: 'Search procurement centers...', distance: 'Distance', allDistances: 'All distances', status: 'Status', allStatuses: 'All statuses', waiting: 'Waiting Time', anyWait: 'Any wait', found: 'centers found', availableSlots: 'available slots', averageWait: 'average waiting time', minutes: 'min', hoursShort: 'hr', hours: 'Operating hours', slots: 'slots', away: 'km away', low: 'Low', medium: 'Medium', high: 'High', opensTomorrow: 'Opens tomorrow', locationUnsupported: 'Location is not supported by this browser. Showing demo centers.', requesting: 'Requesting your location...', centersNear: 'Centers near', liveUnavailable: 'Live center data unavailable. Showing demo centers.', permissionDenied: 'Location permission was denied. Showing demo centers.', open: 'Open', almostFull: 'Almost Full', closed: 'Closed', viewMap: 'View on Map', book: 'Book Slot', names: { 'Vijayawada Procurement Center': 'Vijayawada Procurement Center', 'Guntur Procurement Center': 'Guntur Procurement Center', 'Mangalagiri Procurement Center': 'Mangalagiri Procurement Center', 'Amaravati Procurement Center': 'Amaravati Procurement Center', 'Gannavaram Procurement Center': 'Gannavaram Procurement Center', 'Ibrahimpatnam Procurement Center': 'Ibrahimpatnam Procurement Center' }, demoMap: 'Interactive map will be available here.', noMatch: 'No centers match your filters.', tryAnother: 'Try another search or filter.' },
  booking: { title: 'Book a Procurement Slot', selectCrop: 'Select Crop', chooseCrop: 'Choose a crop', selectQuantity: 'Select Quantity', quantityPlaceholder: 'Enter quantity in kg', selectCenter: 'Select Procurement Center', selectDate: 'Select Date', selectSlot: 'Select Time Slot', chooseDetails: 'Please select a crop, quantity, center, date, and time slot before continuing.', confirmTitle: 'Confirm Your Booking', verify: 'Please verify your details before confirming.', successTitle: 'Booking Confirmed!', successMessage: 'Your procurement slot has been successfully booked.', bookingId: 'Booking ID', confirmed: 'Confirmed', chooseCenter: 'Select a center' },
  queue: { token: 'Token Number', position: 'Queue Position', waiting: 'Waiting for Procurement', submitted: 'Request Submitted', allocated: 'Slot Allocated', arrived: 'Arrived at Center', completed: 'Procurement Completed', pending: 'Pending', current: 'Current status' },
  status: { title: 'Procurement Status', description: 'Track the procurement status of all your bookings.', noBookings: 'No procurement bookings yet.', confirmedAppear: 'Confirmed bookings will appear here.' },
  notifications: { title: 'Notifications', description: 'Stay updated about your procurement activities.', markRead: 'Mark All as Read', clear: 'Clear All', unread: 'unread updates', empty: 'No notifications yet.' },
  history: { eyebrow: 'Farmer bookings', title: 'My Bookings', description: 'Review your current and upcoming procurement slot bookings.', heading: 'Booking History', newBooking: 'New Booking' },
  messages: { loginSuccess: 'Login successful. Welcome back.', demo: 'This is demo data. Backend integration can be added later.', apiFallback: 'Live center data unavailable. Showing demo centers.' }
};
