window.farmerTranslations = window.farmerTranslations || {};
window.farmerTranslations.te = {
  language: 'తెలుగు',
  languageLabel: '🌐 తెలుగు | English',
  common: {
    home: 'హోమ్', dashboard: 'డ్యాష్‌బోర్డ్', centers: 'కేంద్రాలు', bookings: 'బుకింగ్‌లు', myBookings: 'నా బుకింగ్‌లు', procurement: 'కొనుగోలు', notifications: 'నోటిఫికేషన్‌లు', profile: 'ప్రొఫైల్', logout: 'లాగ్ అవుట్', login: 'లాగిన్', register: 'రిజిస్టర్', back: 'వెనుకకు', backDashboard: 'డ్యాష్‌బోర్డ్‌కు వెనుకకు', cancel: 'రద్దు', continue: 'కొనసాగించు', confirm: 'బుకింగ్ నిర్ధారించు', viewBookings: 'నా బుకింగ్‌లు చూడండి', viewStatus: 'కొనుగోలు స్థితి చూడండి', backHome: 'హోమ్‌కు వెనుకకు', save: 'సేవ్', close: 'మూసివేయి', farmer: 'రైతు', select: 'ఎంచుకోండి', status: 'స్థితి', date: 'తేదీ', time: 'సమయం', crop: 'పంట', quantity: 'పరిమాణం', center: 'కొనుగోలు కేంద్రం', mobile: 'మొబైల్'
  },
  home: { how: 'ఇది ఎలా పనిచేస్తుంది', welcome: 'మీ కొనుగోలు, బుకింగ్‌లు మరియు కేంద్ర సందర్శనలను ఒకే చోట నిర్వహించండి.', nearby: 'సమీప కేంద్రాలు', viewCenters: 'కేంద్రాలు చూడండి', findCenter: 'కొనుగోలు కేంద్రం కనుగొనండి', bookSlot: 'స్లాట్ బుక్ చేయండి', viewBookings: 'బుకింగ్‌లు చూడండి', viewProcurement: 'కొనుగోలు చూడండి', viewNotifications: 'నోటిఫికేషన్‌లు చూడండి', notifications: 'మీ బుకింగ్‌లు మరియు కొనుగోలుకు సంబంధించిన ముఖ్యమైన సమాచారం చూడండి.' },
  login: { title: 'రైతు లాగిన్', phone: 'మొబైల్ నంబర్', phonePlaceholder: 'మీ మొబైల్ నంబర్ నమోదు చేయండి', password: 'పాస్‌వర్డ్', passwordPlaceholder: 'మీ పాస్‌వర్డ్ నమోదు చేయండి', submit: 'లాగిన్', noAccount: 'ఖాతా లేదా?', register: 'రిజిస్టర్', invalid: 'మొబైల్ నంబర్ లేదా పాస్‌వర్డ్ సరిపోలలేదు.', noAccountFound: 'ఖాతా కనబడలేదు. ముందుగా రిజిస్టర్ చేయండి.' },
  registration: { title: 'మీ రైతు ఖాతాను సృష్టించండి', fullName: 'పూర్తి పేరు', fullNamePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి', phone: 'మొబైల్ నంబర్', password: 'పాస్‌వర్డ్', passwordPlaceholder: 'పాస్‌వర్డ్ సృష్టించండి', confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి', confirmPlaceholder: 'మీ పాస్‌వర్డ్ నిర్ధారించండి', state: 'రాష్ట్రాన్ని ఎంచుకోండి', district: 'జిల్లాను ఎంచుకోండి', submit: 'ఖాతా సృష్టించండి', success: 'రిజిస్ట్రేషన్ విజయవంతమైంది! ఇప్పుడు లాగిన్ చేయవచ్చు.' },
  center: { nearby: 'సమీపంలోని కొనుగోలు కేంద్రాలు', description: 'సమీప కేంద్రాలను కనుగొని, అందుబాటును చూసి, మీ స్లాట్ బుక్ చేయండి.', search: 'కొనుగోలు కేంద్రాల కోసం వెతకండి...', distance: 'దూరం', allDistances: 'అన్ని దూరాలు', status: 'స్థితి', allStatuses: 'అన్ని స్థితులు', waiting: 'వేచి ఉండే సమయం', anyWait: 'ఏదైనా సమయం', found: 'కేంద్రాలు కనుగొనబడ్డాయి', availableSlots: 'అందుబాటులో ఉన్న స్లాట్‌లు', averageWait: 'సగటు వేచి ఉండే సమయం', minutes: 'నిమి', hoursShort: 'గం', hours: 'పని వేళలు', slots: 'స్లాట్‌లు', away: 'కిమీ దూరంలో', low: 'తక్కువ', medium: 'మధ్యస్థం', high: 'ఎక్కువ', opensTomorrow: 'రేపు తెరుస్తుంది', locationUnsupported: 'ఈ బ్రౌజర్‌లో లొకేషన్ అందుబాటులో లేదు. డెమో కేంద్రాలను చూపిస్తున్నాము.', requesting: 'మీ లొకేషన్‌ను పొందుతున్నాము...', centersNear: 'సమీపంలోని కేంద్రాలు', liveUnavailable: 'లైవ్ కేంద్ర సమాచారం అందుబాటులో లేదు. డెమో కేంద్రాలను చూపిస్తున్నాము.', permissionDenied: 'లొకేషన్ అనుమతి నిరాకరించబడింది. డెమో కేంద్రాలను చూపిస్తున్నాము.', open: 'అందుబాటులో ఉంది', almostFull: 'దాదాపు నిండింది', closed: 'మూసివేయబడింది', viewMap: 'మ్యాప్‌లో చూడండి', book: 'స్లాట్ బుక్ చేయండి', names: { 'Vijayawada Procurement Center': 'విజయవాడ కొనుగోలు కేంద్రం', 'Guntur Procurement Center': 'గుంటూరు కొనుగోలు కేంద్రం', 'Mangalagiri Procurement Center': 'మంగళగిరి కొనుగోలు కేంద్రం', 'Amaravati Procurement Center': 'అమరావతి కొనుగోలు కేంద్రం', 'Gannavaram Procurement Center': 'గన్నవరం కొనుగోలు కేంద్రం', 'Ibrahimpatnam Procurement Center': 'ఇబ్రహీంపట్నం కొనుగోలు కేంద్రం' }, demoMap: 'ఇంటరాక్టివ్ మ్యాప్ త్వరలో అందుబాటులో ఉంటుంది.', noMatch: 'మీ ఫిల్టర్‌లకు కేంద్రాలు సరిపోలలేదు.', tryAnother: 'మరొక శోధన లేదా ఫిల్టర్ ప్రయత్నించండి.' },
  booking: { title: 'కొనుగోలు స్లాట్ బుక్ చేయండి', selectCrop: 'పంటను ఎంచుకోండి', chooseCrop: 'పంటను ఎంచుకోండి', selectQuantity: 'పరిమాణాన్ని ఎంచుకోండి', quantityPlaceholder: 'కిలోల్లో పరిమాణం నమోదు చేయండి', selectCenter: 'కొనుగోలు కేంద్రాన్ని ఎంచుకోండి', selectDate: 'తేదీని ఎంచుకోండి', selectSlot: 'సమయ స్లాట్‌ను ఎంచుకోండి', chooseDetails: 'కొనసాగించే ముందు పంట, పరిమాణం, కేంద్రం, తేదీ మరియు సమయ స్లాట్‌ను ఎంచుకోండి.', confirmTitle: 'మీ బుకింగ్‌ను నిర్ధారించండి', verify: 'నిర్ధారించే ముందు వివరాలను పరిశీలించండి.', successTitle: 'బుకింగ్ నిర్ధారించబడింది!', successMessage: 'మీ కొనుగోలు స్లాట్ విజయవంతంగా బుక్ చేయబడింది.', bookingId: 'బుకింగ్ ఐడి', confirmed: 'నిర్ధారించబడింది', chooseCenter: 'కేంద్రాన్ని ఎంచుకోండి' },
  queue: { token: 'టోకెన్ నంబర్', position: 'క్యూలో స్థానం', waiting: 'కొనుగోలు కోసం వేచి ఉంది', submitted: 'అభ్యర్థన పంపబడింది', allocated: 'స్లాట్ కేటాయించబడింది', arrived: 'కేంద్రానికి చేరుకున్నారు', completed: 'కొనుగోలు పూర్తయింది', pending: 'పెండింగ్', current: 'ప్రస్తుత స్థితి' },
  status: { title: 'కొనుగోలు స్థితి', description: 'మీ అన్ని బుకింగ్‌ల కొనుగోలు స్థితిని ట్రాక్ చేయండి.', noBookings: 'ఇంకా కొనుగోలు బుకింగ్‌లు లేవు.', confirmedAppear: 'నిర్ధారించిన బుకింగ్‌లు ఇక్కడ కనిపిస్తాయి.' },
  notifications: { title: 'నోటిఫికేషన్‌లు', description: 'మీ కొనుగోలు కార్యకలాపాల గురించి సమాచారం పొందండి.', markRead: 'అన్నీ చదివినట్లు గుర్తించండి', clear: 'అన్నీ తొలగించండి', unread: 'చదవని అప్‌డేట్‌లు', empty: 'ఇంకా నోటిఫికేషన్‌లు లేవు.' },
  history: { eyebrow: 'రైతు బుకింగ్‌లు', title: 'నా బుకింగ్‌లు', description: 'మీ ప్రస్తుత మరియు రాబోయే కొనుగోలు స్లాట్ బుకింగ్‌లను పరిశీలించండి.', heading: 'బుకింగ్ చరిత్ర', newBooking: 'కొత్త బుకింగ్' },
  messages: { loginSuccess: 'లాగిన్ విజయవంతమైంది. తిరిగి స్వాగతం.', demo: 'ఇది డెమో డేటా. బ్యాక్‌ఎండ్ అనుసంధానం తరువాత జోడించవచ్చు.', apiFallback: 'లైవ్ కేంద్ర సమాచారం అందుబాటులో లేదు. డెమో కేంద్రాలను చూపిస్తున్నాము.' }
};
